routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\categoryController;
use App\Http\Controllers\productController;
use App\Http\Controllers\loginController;
use App\Http\Controllers\userController;
use App\Http\Controllers\messageController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//login controller route
Route::get('/',[loginController::class,'index'])->name('/');
Route::post('validate',[loginController::class,'validatedata'])->name('validate');
Route::get('destroy',[loginController::class,'destroy'])->name('destroy');
Route::get('/home',[loginController::class,'redirectToHome'])->name('home');

Route::get('messagetype/{id}',[userController::class,'messagetype'])->name('messagetype');


Route::resource('category',categoryController::class);
Route::resource('product',productController::class);
Route::resource('user',userController::class);
Route::resource('login',loginController::class);
Route::resource('message',messageController::class);

app/Models/product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class product extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable=['productName','category_id','productPrice','Image'];

    public function category(){
        return $this->belongsTo('App\Models\category','id','category_id');
    }
}

app/Http/Controllers/productController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\product;
use App\Models\category;
use Session;

class productController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->session()->get('uid')!=""){
            $products=product::all();
            return view('product.index',compact('products'));            
        }    
        else{
            return redirect()->route('/')->with('loginstate','login first');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.addproduct');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $request->validate([
            'productName'=>'required',
            'category'=>'required',
            'image'=>'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'price'=>'required',   
        ]);

        $fileName = time().'.'.$request->file('image')->extension();  
        $request->file('image')->move(public_path('products'), $fileName);
        
        category::find($request['category'])->products()->create(['productName' => $request['productName'],
                         'category_id' => $request['category'],
                         'Image' => $fileName,
                         'productPrice' => $request['price']
                     ]);


        return redirect()->route('product.index');
       
    }

    /**
     * Display the specified resource.
     *      
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data=product::find($id);
        return view('product.editproduct',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
        if($request->file('Image')){
            $fileName = time().'.'.$request->file('Image')->extension();  
            $request->file('Image')->move(public_path('products'), $fileName);
            product::find($id)->update(['productName'=>$request['productName'],
                                        'category_id'=>$request['category_id'],     
                                        'Image' => $fileName,
                                        'productPrice' => $request['productPrice'],
                                        ]);
        }
        else{
            product::find($id)->update($request->all());    
        }
          

        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        product::find($id)->delete();
        return redirect()->route('product.index');
    }
}

resources/views/product/addproduct.blade.php
@extends('layout.mainlayout');


@section('title')

@stop

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Add PRoduct</a></li>
@stop

@section('extra')
	<div></div>
@stop


@section('card-title')
	Add New
@stop

@section('card-content')

     @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
	<form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
	@csrf          
        <div class="form-group">
            <label>Product Name</label>
            <input type="text" name="productName" class="form-control">
        </div>
        <div class="form-group">
            <label>category</label>
            <select name="category" class="form-control">
                @php 
                    $categorys=App\Models\category::all();
                @endphp
                @foreach($categorys as $category)
                    <option value="{{ $category->id }}">{{ $category->categoryName }}</option>
                @endforeach
            </select>
        </div>
        <div class="mb-3">
            <label for="formFile" class="form-label">Product Image</label><br>
            <input class="" type="file" name="image" id="img_prd">
            <img   class="ml-3 mt-3" id="preview-image" width="300px">
        </div>
        <div class="form-group">
            <label>Price</label>
            <input type="text" name="price" class="form-control">
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success" name="submit" value="Add">
            <input type="Reset" class="btn btn-danger" value="Reset">
        </div>
    </form>
	
@stop

resources/views/product/editproduct.blade.php
@extends('layout.mainlayout');


@section('title')

@stop

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Edit Product</a></li>
@stop

@section('extra')
	<div></div>
@stop


@section('card-title')
	Edit Product
@stop

@section('card-content')

     @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
	<form action="{{ route('product.update',$data->id) }}" method="POST" enctype="multipart/form-data">
	@csrf          
    @method('PUT')
        <div class="form-group">
            <label>Product Name</label>
            <input type="text" name="productName" class="form-control" value="{{ $data->productName }}">
        </div>
        <div class="form-group">
            <label>category</label>
            <select name="category_id" class="form-control">
                @php 
                    $categorys=App\Models\category::all();
                @endphp
                @foreach($categorys as $category)
                    @if($category->id==$data->category_id)
                        <option value="{{ $category->id }}" selected>{{ $category->categoryName }}</option>
                    @else
                        <option value="{{ $category->id }}">{{ $category->categoryName }}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <div class="mb-3">
            <label for="formFile" class="form-label">Product Image</label><br>
            <input type="file" id="img_prd" name="Image"><br>
            <img src="/products/{{$data->Image}}" class="ml-3 mt-3" id="preview-image" width="300px">
        </div>
        <div class="form-group">
            <label>Price</label>
            <input type="text" name="productPrice" class="form-control" value="{{ $data->productPrice }}">
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success" name="submit" value="Update">
            <input type="Reset" class="btn btn-danger" value="Reset">
        </div>
    </form>
	
@stop

resources/views/product/index.blade.php
@extends('layout.mainlayout')


@section('title')

@stop

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Product</a></li>
@stop

@section('extra')
	<div><a href="{{ route('product.create') }}" class="btn btn-success">Add Product</a></div>
@stop


@section('card-title')
	Products
@stop

@section('card-content')
	
	<table class="table text-center">
		<thead>
			<tr>
				<td class="text-center">No</td>
				<td class="text-center">Name</td>
				<td class="text-center">Category</td>
				<td class="text-center">price</td>
				<td class="text-center">Image</td>
				<td class="text-center">Actions</td>
			</tr>
		</thead>
	@foreach($products as $product)
		<tr>
			<td class="text-center">{{ $product->id }}</td>
			<td class="text-center">{{ $product->productName }}</td>
			<td class="text-center">
				@php
					$category=App\Models\category::find($product->category_id);
					echo $category->categoryName;
				@endphp	
			</td>
			<td class="text-center">{{ $product->productPrice }}</td>
			<td class="text-center"><img src="/products/{{$product->Image}}" width="150px" height="150px"></td>
			<td class="text-center">
				<form action="{{ route('product.destroy',$product->id) }}" method="POST">
					@csrf
					<a href="{{ route('product.edit',$product->id) }}" class="btn btn-primary">Edit</a>
					@method('DELETE')
					<input type="submit" name="submit" value="Delete" class="btn btn-danger">
				</form>
			</td>
		</tr>
	@endforeach
	</table>
@stop