routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\categoryController;
use App\Http\Controllers\productController;
use App\Http\Controllers\loginController;
use App\Http\Controllers\userController;
use App\Http\Controllers\messageController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//login controller route
Route::get('/',[loginController::class,'index'])->name('/');
Route::post('validate',[loginController::class,'validatedata'])->name('validate');
Route::get('destroy',[loginController::class,'destroy'])->name('destroy');
Route::get('/home',[loginController::class,'redirectToHome'])->name('home');

Route::get('messagetype/{id}',[userController::class,'messagetype'])->name('messagetype');


Route::resource('category',categoryController::class);
Route::resource('product',productController::class);
Route::resource('user',userController::class);
Route::resource('login',loginController::class);
Route::resource('message',messageController::class);

app/Models/category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\product;

class category extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable=['categoryName','status'];

    public function products()
    {
        return $this->hasMany('App\Models\product','category_id','id');
    }
}

app/Http/Controllers/categoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\category;

class categoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        if($request->session()->get('uid')!=""){

            $categories=category::all();
            return view('category.index',compact('categories'));
        }
        else{
            return redirect()->route('/');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.addnew');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //$categoryName=$request['categoryName'];
        category::create($request->all());
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data=category::find($id);
        return view('category.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        category::find($id)->update($request->all());
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        category::find($id)->delete();
        return redirect()->route('category.index');
    }
}

resources/views/category/addnew.blade.php
@extends('layout.mainlayout');


@section('title')
Add New Category	
@stop

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Add Category</a></li>
@stop

@section('extra')
	<div></div>
@stop


@section('card-title')
	Add New
@stop

@section('card-content')
	<form action="{{ route('category.store') }}" method="POST">
	@csrf          
        <div class="form-group">
        <label>Category Name</label>
        <input type="text" name="categoryName" class="form-control">
        </div>
        <div class="form-group">
        <label>Status</label>
        <select name="status" class="form-control">
            <option value="0">Deactive</option>
            <option value="1">Active</option>
        </select>
        </div>
        <div class="form-group">
        <input type="submit" class="btn btn-success" name="submit" value="Add">
        <input type="Reset" class="btn btn-danger" value="Reset">
        </div>
    </form>
	
@stop

resources/views/category/edit.blade.php
@extends('layout.mainlayout');


@section('title')
Edit Category	
@stop

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Edit Category</a></li>
@stop

@section('extra')
	<div></div>
@stop


@section('card-title')
	Edit
@stop

@section('card-content')
	<form action="{{ route('category.update',$data->id) }}" method="POST">
	@csrf     
    @method('patch')     
        <div class="form-group">
        <label>Category Name</label>
        <input type="text" name="categoryName" class="form-control" value="{{$data->categoryName}}">
        </div>
        <div class="form-group">
        <label>Status</label>
        <select name="status" class="form-control">
            @if($data->status==0)
            <option value="0" selected>Deactive</option>
            @else
            <option value="1">Active</option>
            @endif
        </select>
        <div class="form-group">
        <input type="submit" class="btn btn-success" name="submit" value="Update">
        <input type="Reset" class="btn btn-danger" value="Reset">
        </div>
    </form>
	
@stop

resources/views/category/index.blade.php
@extends('layout.mainlayout')


@section('title')
Category	
@stop

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Category</a></li>
@stop

@section('extra')
	<div><a href="{{ route('category.create') }}" class="btn btn-success">Add Category</a></div>
@stop


@section('card-title')
	Categorys
@stop

@section('card-content')
	
	<table class="table text-center">
		<thead>
			<tr>
				<td class="text-center">No</td>
				<td class="text-center">Category</td>
				<td class="text-center">state</td>
				<td class="text-center">Actions</td>
			</tr>
		</thead>
	@foreach($categories as $category)
		<tr>
			<td class="text-center">{{ $category->id }}</td>
			<td class="text-center">{{ $category->categoryName }}</td>
			<td class="text-center">
				@if($category->status==0)
					Deactive
				@else
					Active
				@endif
			</td>
			<td class="text-center">
				<form action="{{ route('category.destroy',$category->id) }}" method="POST">
					@csrf
					<a href="{{ route('category.edit',$category->id) }}" class="btn btn-primary">Edit</a>
					@method('DELETE')
					<input type="submit" name="submit" value="Delete" class="btn btn-danger">
				</form>
			</td>
		</tr>
	@endforeach
	</table>
@stop