routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\categoryController;
use App\Http\Controllers\productController;
use App\Http\Controllers\loginController;
use App\Http\Controllers\userController;
use App\Http\Controllers\messageController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//login controller route
Route::get('/',[loginController::class,'index'])->name('/');
Route::post('validate',[loginController::class,'validatedata'])->name('validate');
Route::get('destroy',[loginController::class,'destroy'])->name('destroy');
Route::get('/home',[loginController::class,'redirectToHome'])->name('home');

Route::get('messagetype/{id}',[userController::class,'messagetype'])->name('messagetype');


Route::resource('category',categoryController::class);
Route::resource('product',productController::class);
Route::resource('user',userController::class);
Route::resource('login',loginController::class);
Route::resource('message',messageController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'image',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/userController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class userController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->session()->get('uid')!=""){
            $users=User::all();
            return view('user.index',compact('users'));            
        }    
        else{
            return redirect()->route('/')->with('loginstate','login first');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('login.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //echo "<pre>";
        //print_r($request->all());die();
        $encryption=$this->encryption($request['password']);
        if($request->file('image')){

            $filename=time().'.'.$request->file('image')->extension();
            $request->file('image')->move(public_path('users'),$filename);
            User::create(['name'=>$request['name'],'email'=>$request['email'],'image'=>$filename,'password'=>$encryption]);
        }
        else{
            User::create(['name'=>$request['name'],'email'=>$request['email'],'image'=>'null','password'=>$encryption]);   
        }
        return redirect()->route('user.index');
    }

    public static function encryption($text)
    {
        $ciphering = "AES-128-CTR";

        $iv_length = openssl_cipher_iv_length($ciphering);
        $options = 0;

        // Non-NULL Initialization Vector for encryption
        $encryption_iv = '1234567891011121';

        // Store the encryption key
        $encryption_key = "a1b2c3d4e5f6g7h8";


        $encryption = openssl_encrypt($text, $ciphering,$encryption_key, $options, $encryption_iv);

        return $encryption;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function messagetype(Request $request)
    {
        $id=$request['id'];
        return view('user.message',compact('id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data=user::find($id);
        return view('user.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //$encryption=$this->encryption($request['password']);
        if($request->file('image')){

            $filename=time().'.'.$request->file('image')->extension();
            $request->file('image')->move(public_path('users'),$filename);

            User::find($id)->update(['name'=>$request['name'],'email'=>$request['email'],'image'=>$filename]);
        }
        else{
            User::find($id)->update(['name'=>$request['name'],'email'=>$request['email']]);   
        }
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('user.index');
    }
}

resources/views/user/edit.blade.php
@extends('layout.mainlayout');


@section('title')

@stop

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Edit User</a></li>
@stop

@section('extra')
	<div></div>
@stop


@section('card-title')
	Edit User
@stop

@section('card-content')

     @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
	<form action="{{ route('user.update',$data->id) }}" method="POST" enctype="multipart/form-data">
	@csrf          
    @method('PUT')
        <div class="form-group">
            <label>User Name</label>
            <input type="text" name="name" class="form-control" value="{{ $data->name }}">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" name="email" class="form-control" value="{{ $data->email }}">
        </div>
        <div class="mb-3">
            <label for="formFile" class="form-label">User Image</label><br>
            <input type="file" id="img_prd" name="image"><br>
            <img src="/users/{{$data->image}}" class="ml-3 mt-3" id="preview-image" width="300px">
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success" name="submit" value="Update">
            <input type="Reset" class="btn btn-danger" value="Reset">
        </div>
    </form>
	
@stop

resources/views/user/index.blade.php
@extends('layout.mainlayout')


@section('title')

@stop

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">User</a></li>
@stop

@section('extra')
	<div><a href="{{ route('user.create') }}" class="btn btn-success">Add User</a></div>
@stop


@section('card-title')
	Products
@stop

@section('card-content')
	
	<table class="table text-center">
		<thead>
			<tr>
				<td class="text-center">No</td>
				<td class="text-center">Name</td>
				<td class="text-center">Email</td>
				<td class="text-center">Image</td>
				<td class="text-center">Message</td>
			</tr>
		</thead>
	@isset($users)	
		@foreach($users as $user)
			<tr>
				<td class="text-center">{{ $user->id }}</td>
				<td class="text-center">{{ $user->name }}</td>
				<td class="text-center">{{ $user->email }}</td>
				<td><img src="/users/{{$user->image}}" width="100px" height="100px"></td>
				<td><a href="{{ route('messagetype', $user->id) }}" class="btn btn-success">Message</a></td>
			</tr>
		@endforeach
	@endisset
	</table>
@stop

resources/views/user/message.blade.php
@extends('layout.mainlayout');


@section('title')

@stop

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Send Message</a></li>
@stop

@section('extra')
	<div></div>
@stop


@section('card-title')
	Message
@stop

@section('card-content')

     @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
	<form action="{{route('message.store')}}" method="POST" enctype="multipart/form-data">
	@csrf          
        
        <input type="hidden" name="s_id" value="{{$id}}">

        <div class="form-group">
            <label>category</label>
            <select name="r_id" class="form-control" required>
                @php 
                    $users=App\Models\User::all();
                @endphp
                @foreach($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
            </select>
        </div>
        
        <div class="form-group">
            <label>Your Message</label>
            <input type="text" name="message" class="form-control" placeholder="Enter Message">
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success" name="submit" value="Send">
        </div>
    </form>
	
@stop